/**
 * URDiary 手機 E2E 核心旅程（v2.3 task 3.2）。
 *
 * 這個檔案的 8 個 test() 刻意用 test.describe.serial() 依序執行、共用同一個
 * 手動建立的 page（beforeAll 建立、afterAll 關閉），不是各自獨立的
 * page/context fixture——後面的流程本來就依賴前面流程留下的狀態（對話
 * →結束對話產生日記→日記列表要看得到剛生成的那篇；日曆 CRUD 也需要先
 * 登入）。serial 模式下若前面某個 test 失敗，Playwright 會自動跳過後面
 * 剩下的 test（而不是繼續在壞掉的狀態上瞎跑），這與分開寫成互相獨立的
 * test 各自重新註冊帳號相比，更貼近一個真實使用者一次坐下來的完整操作，
 * 也讓 `npx playwright test` 的摘要輸出直接對應 task brief 列出的 8 個
 * flow，每個 flow 一行 pass/fail。
 *
 * 因為手動呼叫 browser.newContext()（不是用內建的 page/context fixture），
 * project 設定的 viewport/UA/touch 選項不會自動套用——device-profiles.js
 * 的 contextOptionsFor() 明確把該 project 的裝置描述轉成 newContext()
 * 選項，baseURL 也要在這裡手動補上（fixture 平常會自動注入，這裡繞過了
 * fixture 就必須自己做）。
 *
 * ---------------------------------------------------------------------
 * 「等某個回覆送達」該怎麼斷言：兩個實測踩過的坑，以及為什麼最後選定
 * 「排除思考中氣泡後的訊息『數量』增加」這個寫法
 * ---------------------------------------------------------------------
 * stub 供應商對同一種角色（例如一般對話的 "companion"）永遠回傳同一句
 * 固定文字 STUB_CHAT_REPLY——這對「斷言用哪種寫法」是關鍵限制：
 *
 *   坑 1（純文字比對，不看數量）：sendMessage()/attemptSend() 送出後會先
 *   插入一顆「思考中」佔位氣泡（chat_module.js 的 addThinkingMessage()），
 *   它也帶 .chat-message.system-message class。若改成「看訊息數量有沒有
 *   變多」，數量在真正回覆送達「之前」（使用者訊息 + 佔位氣泡）就已經先
 *   到達預期值，測試會在回覆真正落地前就誤判送出完成，緊接著的動作因此
 *   撞上 chat_module.js 的 isProcessing 忙碌鎖（endChat() 靜默提早
 *   return，只彈一個「忙碌中」toast，不會真的呼叫後端）。
 *
 *   坑 2（純文字比對 + .last()，不看數量）：這個帳號全新建立，登入後
 *   requestDailyCheckin() 會非同步要一句「今日首次開啟」的問候，跟使用者
 *   自己送出的訊息各自獨立、非同步進行，且文字與一般回覆完全相同——為了
 *   排除「.last() 抓到的其實是問候」這個模糊，一度改成「等特定文字出現，
 *   用 .last() 取最新一個」。但這仍然不夠：`.last()` 找的是「目前 DOM 裡
 *   最後一個符合文字的元素」，如果同一個 session 裡「更早之前」已經有過
 *   一句一模一樣文字的回覆（例如上一個 test 自己送出的訊息、或前一輪的
 *   回覆），那個舊元素本身早已經穩定可見，`.last()` 會立刻比對成功——
 *   跟這一輪「有沒有真的送出新訊息、拿到新回覆」完全無關，一樣會在回覆
 *   還沒送達前就誤判通過。
 *
 * 兩個坑合起來，唯一站得住腳的寫法是「先精準排除思考中佔位氣泡（一個
 * CSS class 選取器就能做到），再看這個排除後的『數量』有沒有真的增加」
 * ——數量變化才能證明「有一則新的、真正落地的訊息」，光憑文字內容
 * （不管有沒有 .last()）都無法排除「畫面上早就有一個看起來一樣的舊元素」
 * 這個可能性。`realSystemMessages`（見下方）就是這個排除後的選取器，全檔
 * 一致使用。「register and login」測試額外在登入後等到網路完全靜置
 * （networkidle），讓每日問候在這裡就先徹底落地，後面的訊息數量基準點
 * 才不會被問候的非同步時序汙染。
 */
'use strict';

const { test, expect } = require('@playwright/test');
const { BASE_URL } = require('./e2e-env');
const { IPHONE_14, PIXEL_7, contextOptionsFor } = require('./device-profiles');

// 必須與 backend/app/providers/stub_provider.py 的同名常數逐字相同。兩邊
// 沒有共用來源（Python 常數無法被 CommonJS require），修改其中一處的文字
// 時務必同步修改另一處——這正是該檔案檔頭要求的「先搜尋 desktop/e2e/」。
const STUB_CHAT_REPLY =
    "[urdiary-e2e-stub] Hi, I'm the deterministic stub reply used by the Playwright test suite.";
const STUB_DIARY_BODY =
    '[urdiary-e2e-stub] Today was a quiet, ordinary day. This diary entry was generated by ' +
    'the deterministic Playwright test stub, not a real model.';
// 對話結束成功的系統訊息（backend/app/api/routes/chat.py 的 end_chat_session；
// stub 的互動筆記更新永遠成功，interaction_note_error 恆為 None，因此固定
// 是這一句，不會是「日記已生成，但互動筆記更新失敗」那句）。
const DIARY_DONE_TEXT = '對話已結束並生成摘要';

// 密碼需符合 utils/password_validator：長度>=8、大小寫、數字、特殊字元。
const STRONG_PASSWORD = 'E2eTest!2026';

function uniqueUsername(prefix) {
    return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * 防禦性地關掉「啟動時的錯誤提示」（若有）。
 *
 * 這是既有行為，不是本次改動引入的：main.js 在 DOMContentLoaded 會無條件
 * 呼叫 DiaryModule.init() → loadDiaries()，早於登入完成、還沒有 token，
 * 一定拿到 401；UIManager.showError() 因此彈出 #error-container，它的
 * z-index (1100，見 css/components.css) 蓋過登入對話框 (1000)，會擋住
 * #create-user-btn 的點擊。任何人在全新裝置上第一次啟動 App 都會看到同一
 * 個提示，跟這次新增的 stub/E2E 改動無關——已記錄在 task-3.2-report.md
 * 的「發現但非本次任務範圍」一節；這裡只是讓 E2E 不被這個既有的無害提示
 * 卡住。
 */
async function dismissStartupErrorIfAny(page) {
    const closeBtn = page.locator('#close-error-btn');
    if (await closeBtn.isVisible().catch(() => false)) {
        await closeBtn.click();
    }
}

test.describe.serial('URDiary mobile E2E journey', () => {
    test.setTimeout(60000);

    /** @type {import('@playwright/test').Page} */
    let page;
    // 排除「思考中」佔位氣泡後的系統訊息——見檔頭的坑 1/坑 2 說明，全檔
    // 判斷「有沒有一則新回覆真正落地」一律靠這個選取器的「數量」變化。
    /** @type {import('@playwright/test').Locator} */
    let realSystemMessages;

    test.beforeAll(async ({ browser }, testInfo) => {
        const deviceDescriptor = testInfo.project.name === 'Pixel 7' ? PIXEL_7 : IPHONE_14;
        const context = await browser.newContext({
            ...contextOptionsFor(deviceDescriptor),
            baseURL: BASE_URL,
        });
        page = await context.newPage();
        realSystemMessages = page.locator('.chat-message.system-message:not(.thinking)');

        // 關掉「結束對話 500ms 後自動切到日記頁」（js/chat_module.js 的
        // endChat()，讀 CONFIG.APP.AUTO_SWITCH_TO_DIARY_AFTER_END，預設
        // true）。這個計時器與本測試檔自己明確的分頁導覽（.tab-bar 點擊）
        // 互相賽跑：實測在較慢/併發（兩個 project 併發跑同一個後端）的環境
        // 下，前一輪的計時器會在「下一輪已經明確切回對話頁、正要點結束對話」
        // 的瞬間插進來搶走畫面，導致點擊逾時或撞見不是預期中的視圖。這裡
        // 用 addInitScript（不是一次性的 evaluate）讓每次導覽/reload 都重新
        // 套用——config.js 的 Object.freeze(CONFIG) 只凍住最外層，CONFIG.APP
        // 巢狀物件本身沒被凍結，這裡的指定是合法的。測試改用自己明確的
        // 分頁點擊掌控導覽，不依賴、也不受這個背景計時器影響。
        await page.addInitScript(() => {
            window.addEventListener('DOMContentLoaded', () => {
                if (window.CONFIG && window.CONFIG.APP) {
                    window.CONFIG.APP.AUTO_SWITCH_TO_DIARY_AFTER_END = false;
                }
            });
        });
    });

    test.afterAll(async () => {
        if (page) {
            await page.context().close();
        }
    });

    // 失敗時手動補一張截圖附件——這個檔案不走 page/context fixture，
    // Playwright 內建的「失敗自動截圖」(config 的 use.screenshot) 只掛在
    // fixture 提供的 page 上，這裡繞過了 fixture 就要自己補。
    test.afterEach(async ({}, testInfo) => {
        if (testInfo.status !== testInfo.expectedStatus && page && !page.isClosed()) {
            const screenshotPath = testInfo.outputPath('failure.png');
            await page.screenshot({ path: screenshotPath, fullPage: true }).catch(() => {});
            await testInfo
                .attach('failure-screenshot', { path: screenshotPath, contentType: 'image/png' })
                .catch(() => {});
        }
    });

    test('install readiness: manifest resolves and service worker becomes active', async () => {
        await page.goto('/');

        const manifestHref = await page.locator('link[rel="manifest"]').getAttribute('href');
        expect(manifestHref).toBeTruthy();
        const manifestResponse = await page.request.get(new URL(manifestHref, page.url()).toString());
        expect(manifestResponse.status()).toBe(200);
        const manifestJson = await manifestResponse.json();
        expect(manifestJson.name).toBe('URDiary');

        await page.waitForFunction(
            async () => {
                if (!('serviceWorker' in navigator)) return false;
                const reg = await navigator.serviceWorker.getRegistration();
                return !!(reg && reg.active);
            },
            { timeout: 15000 }
        );
    });

    test('register and login', async () => {
        const username = uniqueUsername('e2e');

        await expect(page.locator('#create-user-btn')).toBeVisible({ timeout: 15000 });
        await dismissStartupErrorIfAny(page);
        await page.click('#create-user-btn');

        await expect(page.locator('#create-user-dialog')).toBeVisible();
        await page.fill('#new-username', username);
        await page.fill('#new-password', STRONG_PASSWORD);
        await page.fill('#confirm-password', STRONG_PASSWORD);
        await page.click('#submit-new-user');

        // 登入成功會關掉所有登入相關對話框、顯示主畫面（main.js 的 enterApp()）。
        await expect(page.locator('#create-user-dialog')).toBeHidden();
        await expect(page.locator('#user-input')).toBeVisible();

        // 登入成功後 main.js 的 loginUser() 會重新初始化 ChatModule，
        // loadChatHistory() 因此觸發一次「今日首次開啟」的每日問候請求
        // （POST /chat/checkin/，interaction_service.daily_checkin）。在這裡
        // （問候的源頭）就把它連同其他登入後的背景請求（日曆/日記初始載入）
        // 一起等到網路完全靜置，後面每個「訊息數量」斷言的起始基準點才不會
        // 被問候的非同步時序汙染（見檔頭的坑 1/坑 2 說明）。networkidle 在
        // 這裡是安全的選擇：這個 App 沒有長輪詢/WebSocket，登入後的背景
        // 請求都是一次性的 fetch，很快就會真的靜置下來。
        await page.waitForLoadState('networkidle');
    });

    test('chat: send a message and receive the stub reply', async () => {
        const before = await realSystemMessages.count();

        await page.fill('#user-input', 'Hello from Playwright E2E (message 1)');
        await page.click('#send-button');

        await expect(
            page.locator('.chat-message.user-message', { hasText: 'message 1' })
        ).toBeVisible();
        await expect(realSystemMessages).toHaveCount(before + 1, { timeout: 15000 });
        await expect(realSystemMessages.last()).toContainText(STUB_CHAT_REPLY);
    });

    test('end chat: a diary entry is generated (run twice to populate the list)', async () => {
        for (let round = 1; round <= 2; round++) {
            // 明確切回對話頁再開始這一輪：CONFIG.APP.AUTO_SWITCH_TO_DIARY_
            // AFTER_END 已在 beforeAll 關閉，但 chat_module.js 的 endChat()
            // 不論該旗標開關都會再排一個 500ms 的背景 DiaryModule.
            // loadDiaries()（見該檔案）——上一輪結束後不能假設「現在還在
            // 對話頁」，這裡每輪開頭都主動導覽回對話頁一次，不依賴時序。
            await page.click('.tab-bar .nav-item[data-view="chat"]');
            await expect(page.locator('#user-input')).toBeVisible();

            if (round === 2) {
                // round 1 重用上一個 test 留下的對話；round 2 需要新訊息，
                // 否則 generate_enhanced_diary 會走「無對話記錄」的後備文案，
                // 不會呼叫 stub。斷言方式見檔頭說明（排除思考中氣泡後的
                // 訊息數量增加，不能只看文字內容）。
                const beforeSend = await realSystemMessages.count();
                await page.fill('#user-input', `Hello from Playwright E2E (message ${round})`);
                await page.click('#send-button');
                await expect(realSystemMessages).toHaveCount(beforeSend + 1, { timeout: 15000 });
                await expect(realSystemMessages.last()).toContainText(STUB_CHAT_REPLY);
            }

            const beforeEnd = await realSystemMessages.count();
            await page.click('#end-chat-btn');
            await expect(realSystemMessages).toHaveCount(beforeEnd + 1, { timeout: 20000 });
            await expect(realSystemMessages.last()).toContainText(DIARY_DONE_TEXT);
        }

        // 不直接切去日記頁斷言列表：DiaryModule.loadDiaries() 只在 App
        // 啟動時、以及 chat_module.js endChat() 成功後 500ms 的背景計時器
        // 裡被呼叫（見該檔案），單純切換分頁（switchToState）本身不會觸發
        // 重新抓取。兩輪各自獨立的 500ms 背景重整跟這裡的斷言時序賽跑，
        // 會讀到「只看得到第一篇」的過渡態（實測會 flaky）。改成整頁
        // reload——JWT 存在 localStorage，重新整理後仍是登入狀態
        // （main.js 的 isAuthenticated() 檢查），DiaryModule.init() 會用
        // 當下的伺服器狀態重新抓一次列表，讀到的必定是兩輪都已 commit
        // 之後的最終結果，不必再猜背景計時器的時序。
        await page.reload();
        await expect(page.locator('#user-input')).toBeVisible({ timeout: 15000 });

        await page.click('.tab-bar .nav-item[data-view="diary"]');
        await expect(page.locator('.diary-card')).toHaveCount(2, { timeout: 15000 });
    });

    test('diary: scroll the list, open a detail, and go back', async () => {
        const cards = page.locator('.diary-card');
        await expect(cards).toHaveCount(2);
        await expect(cards.first()).toContainText('urdiary-e2e-stub');

        // 捲動互動（brief 明確要求）：即使兩則條目本來就看得到，仍實際觸發
        // 一次捲動，確認容器本身不會出錯。
        await page.locator('.diary-list').evaluate((el) => el.scrollTo(0, el.scrollHeight));

        await cards.first().click();
        await expect(page.locator('.detail-content')).toContainText(STUB_DIARY_BODY, { timeout: 10000 });

        await page.click('#back-to-list-btn');
        await expect(page.locator('.diary-list')).toBeVisible();
        await expect(page.locator('.diary-card')).toHaveCount(2);
    });

    test('calendar: create, edit, and delete an event', async () => {
        await page.click('.tab-bar .nav-item[data-view="calendar"]');
        await expect(page.locator('.calendar-grid .calendar-cell').first()).toBeVisible({ timeout: 15000 });

        const stamp = Date.now();
        // 兩個標題刻意不互為子字串（day-event 的 hasText 是子字串比對），
        // 否則改名後舊標題的斷言仍會「找到」改名後的那筆，False negative。
        const originalTitle = `E2E-Original-${stamp}`;
        const editedTitle = `E2E-Renamed-${stamp}`;

        // create
        await page.click('#calendar-add-btn');
        await expect(page.locator('#event-dialog')).toBeVisible();
        await page.fill('#event-title', originalTitle);
        await page.click('#event-save');

        const originalRow = page.locator('.day-event', { hasText: originalTitle });
        await expect(originalRow).toBeVisible({ timeout: 10000 });

        // edit
        await originalRow.locator('[data-action="edit"]').click();
        await expect(page.locator('#event-dialog')).toBeVisible();
        await page.fill('#event-title', editedTitle);
        await page.click('#event-save');

        const editedRow = page.locator('.day-event', { hasText: editedTitle });
        await expect(editedRow).toBeVisible({ timeout: 10000 });
        await expect(page.locator('.day-event', { hasText: originalTitle })).toHaveCount(0);

        // delete（window.confirm——必須在觸發動作前先掛好 dialog 處理器）
        page.once('dialog', (dialog) => dialog.accept());
        await editedRow.locator('[data-action="delete"]').click();
        await expect(page.locator('.day-event', { hasText: editedTitle })).toHaveCount(0, { timeout: 10000 });
    });

    test('offline banner appears when offline and clears when back online', async () => {
        const banner = page.locator('#connectivity-banner');
        await expect(banner).toHaveAttribute('aria-hidden', 'true');

        await page.context().setOffline(true);
        await expect(banner).toHaveAttribute('aria-hidden', 'false', { timeout: 10000 });
        await expect(banner).toHaveClass(/visible/);

        await page.context().setOffline(false);
        await expect(banner).toHaveAttribute('aria-hidden', 'true', { timeout: 10000 });
    });

    test('mobile layout: single pane + bottom tab bar visible', async () => {
        await expect(page.locator('.tab-bar')).toBeVisible();
        await expect(page.locator('.app-nav')).toBeHidden();

        await page.click('.tab-bar .nav-item[data-view="chat"]');
        await expect(page.locator('#chat-view')).toBeVisible();
        await expect(page.locator('#diary-view')).toBeHidden();
        await expect(page.locator('#calendar-view')).toBeHidden();
        await expect(page.locator('.view-container.active')).toHaveCount(1);

        await page.click('.tab-bar .nav-item[data-view="diary"]');
        await expect(page.locator('#diary-view')).toBeVisible();
        await expect(page.locator('#chat-view')).toBeHidden();
        await expect(page.locator('.view-container.active')).toHaveCount(1);
    });
});
