"""env-gated 的 canned-response 供應商（v2.3 task 3.2：Playwright 手機 E2E 用）。

**這個檔案本身完全沒有旗標檢查**——唯一的守門處是 providers/factory.py 的
build_provider()：只有 stub_llm_allowed()（讀取 URDIARY_ALLOW_STUB_LLM，呼叫
當下讀，不綁 import）回傳 True 時，build_provider 才會建構這個類別的實例。
判斷邏輯集中在單一檔案，稽核「正式環境是否可能誤用 stub」時只需要看
factory.py 一處，不必擔心散落各處的旗標檢查其中一處漏掉。

**絕不要在別處 import 這個模組去繞過 build_provider**——StubProvider 本身
不做任何限制，安全性完全依賴呼叫端只透過 build_provider 取得實例。

回覆內容依 system 訊息判斷這次呼叫的用途（對話 / 日記生成 / 互動筆記更新），
不解析 messages 其餘內容——這些系統角色句本身就是 services/prompt_loader.py
的 get_role() 固定輸出（services/prompts/{lang}/roles.json），比對這幾句
就足以區分三種用途，不需要更複雜的邏輯。

三個常數字串是 Playwright E2E 斷言用的固定錨點（desktop/e2e/*.spec.js）。
改動這裡的文字前，先搜尋 desktop/e2e/ 底下對應的字串，兩邊要一起改。
"""
from typing import List, Dict

from providers.base import LLMProvider

STUB_CHAT_REPLY = (
    "[urdiary-e2e-stub] Hi, I'm the deterministic stub reply used by the "
    "Playwright test suite."
)
STUB_DIARY_BODY = (
    "[urdiary-e2e-stub] Today was a quiet, ordinary day. This diary entry "
    "was generated by the deterministic Playwright test stub, not a real model."
)
STUB_INTERACTION_NOTE = (
    "[urdiary-e2e-stub] Canned interaction note generated by the "
    "Playwright test stub."
)

# 對應 services/prompts/{lang}/roles.json 的角色句（zh-TW / en 都要能對到）。
# 只用來判斷「這次呼叫是不是日記生成 / 互動筆記更新」，不是其餘用途。
_DIARY_WRITER_MARKERS = (
    "你是一位能寫出溫暖、有洞察力日記的助手",
    "an assistant who writes warm, insightful diary entries",
)
_NOTE_TAKER_MARKERS = (
    "你是一位專業的心理陪伴記錄員",
    "professional record keeper for a companionship system",
)


class StubProvider(LLMProvider):
    """canned-response 供應商；只服務 Playwright E2E。

    只能透過 providers.factory.build_provider() 在 stub_llm_allowed() 為
    True 時取得實例——見本檔案檔頭與 factory.py 的說明。
    """

    def chat(self, messages: List[Dict[str, str]], model: str) -> str:
        """忽略 model；依 system 訊息回傳固定內容，絕不呼叫任何外部服務。"""
        system_content = ""
        for message in messages:
            if message.get("role") == "system":
                system_content = message.get("content") or ""
                break

        if any(marker in system_content for marker in _DIARY_WRITER_MARKERS):
            return STUB_DIARY_BODY
        if any(marker in system_content for marker in _NOTE_TAKER_MARKERS):
            return STUB_INTERACTION_NOTE
        return STUB_CHAT_REPLY
